### ISSUE TITLE
Incorrectly defined "rejection region" - t_stat used in plot where critical value should be used

### ISSUE THREAD

**Issue by benjamin-jacobson** [learn-co-curriculum/dsc-two-sample-t-tests-lab#1]
In "Calculating pooled sample variance", the lab is asking to demarcate the rejection region “with vertical lines identifying each critical value that signifies the rejection region.” In the solution they use the t-statistic is used as those cut-off lines, not the t-critical value. 

    ax.axvline(t_stat, color='black', linestyle='--', lw=5)
    ax.axvline(-t_stat, color='black', linestyle='--', lw=5)

Please review/revise as necessary. Thanks!

**Comment by mas16** [comment]
Hi benjamin-jacobson, thanks for posting! The plot has been corrected.
