### ISSUE TITLE
StopIteration Error Raising on SaturnCloud Instance Only

### ISSUE THREAD

**Issue by mark-barbour** [learn-co-curriculum/dsc-two-sample-t-tests-lab#2]
### Canvas Link

https://learning.flatironschool.com/courses/6535/assignments/239232?module_item_id=562072

### Concern

The first concern is that the code blocks in the SC instance are out of order. The "control" variable is called before it is defined in a later code cell. This raises a NameError and is not consistent with the order of the code cells provided in the github repo. Once the code cells are in order, in SC only, it raises a StopIteration error with the solution branch code provided in the github repo. If I run this locally (with the cells in the correct order), I do not get this StopIteration Error. The code runs successfully, but also still retains a semantic error. There are "Orange" bars referenced in the comment of the github repo code for the lab, but all that appears is two overlapping blue bars.

**Comment by bpurdy-ds** [comment]
Since we're moving away from SC, I'm going to close this.
